### ISSUE TITLE
Floyd算法详解 | pursuit's blog

### ISSUE THREAD

**Issue by unique-pure** [unique-pure/commentRes#10]
https://unique-pure.github.io/2020/07/27/floyd/ 

 Floyd算法（邻接矩阵与邻接表实现）1 简介Floyd算法又称为插点法，是一种利用动态规划的思想寻找给定的加权图中多源点之间最短路径的算法，可以正确处理有向图或无向图或负权（但不可存在负权回路)的最短路径问题，同时也被用于计算有向图的传递

**Comment by YueQiuShangDeRen** [comment]
看懂了，谢谢博主:smile:
